image: docker:stable-git

stages:
  - test
  - package

test:
  stage: test
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  artifacts:
    untracked: true
    reports:
      junit: output/junit-1.17.xml
    when: always
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - export TEST_VERSION=oss
    - ./test.sh 1.17
  only:
    - branches

package:
  stage: package
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - ./bin/package.sh
  only:
    - branches
  dependencies:
    - test
  artifacts:
    paths:
      - output/dist/*

before_script:
  - apk add --no-cache bash
