version: '2.1'
services:
  postgres:
    container_name: api-go-postgres
    image: postgres:9.3

  conjur:
    container_name: api-go-conjur

    image: cyberark/conjur:1.3

    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY:
      RAILS_ENV: development
    depends_on:
      - postgres

  cli5:
    image: conjurinc/cli5
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber

  cuke-master:
    container_name: api-go-conjur-v4
    image: registry2.itci.conjur.net/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined
    ports:
      - 443

  test:
    container_name: api-go-test
    build: .
    image: golang:1.15-alpine
    ports:
        - 8080
    depends_on:
      - conjur
    volumes:
      - ./output:/conjur-api-go/output
    environment:
      CONJUR_DATA_KEY:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health
      CONJUR_V4_ACCOUNT: cucumber
      CONJUR_V4_AUTHN_LOGIN: admin
      CONJUR_V4_AUTHN_API_KEY:
      CONJUR_V4_SSL_CERTIFICATE:
      TEST_VERSION:

  dev:
    container_name: api-go-dev
    build: .
    ports:
        - 8080
    depends_on:
      - conjur
    volumes:
      - .:/conjur-api-go
    environment:
      CONJUR_DATA_KEY:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health
      CONJUR_V4_ACCOUNT: cucumber
      CONJUR_V4_AUTHN_LOGIN: admin
      CONJUR_V4_AUTHN_API_KEY:
      CONJUR_V4_SSL_CERTIFICATE:
    entrypoint: sleep
    command: infinity
